version: '3'

networks:
  dem:

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - 5432:5432
    networks:
      - dem
  
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      # PGADMIN_DEFAULT_PASSWORD_FILE: 
    depends_on:
      - postgres
    ports:
      - 6000:80
    networks:
      - dem

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/tasks-api-py-fastapi-postgresql
    depends_on:
      - postgres
    ports:
      - 8000:15400
    networks:
      - dem